generators/urls.py
from django.urls import path

from . import views

app_name = "generators"

urlpatterns = [
    path("npc_names", views.npc_name, name="npc_name"),
    path("character_generation/get_stats", views.get_stats, name="get_stats"),
    path("character_generation/create_pc", views.create_PC, name="create_pc"),
    path("character_generation/level_up_pc", views.level_up_PC, name="level_up_pc"),
]

shadowdark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("generators/", include("generators.urls")),
]

generators/models.py
from django.db import models

# Create your models here.

generators/forms.py
from django import forms
from .game_facts import classes, ancestries, backgrounds
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class ClassChoiceForm(forms.Form):
    ancestry_choice_field = [
        (k, cl) for k, cl in zip(range(len(ancestries)), ancestries)
    ]
    ancestry = forms.ChoiceField(choices=ancestry_choice_field, required=True)
    background_choice_field = [
        (k, ": ".join(background))
        for k, background in zip(range(len(backgrounds)), backgrounds)
    ]
    background = forms.ChoiceField(choices=background_choice_field, required=True)
    class_choice_field = [(k, cl) for k, cl in zip(range(len(classes)), classes)]
    class_ = forms.ChoiceField(choices=class_choice_field, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_action = "create_pc"
        self.helper.add_input(Submit("submit", "Create PC"))

generators/views.py
from django.shortcuts import render, redirect

from .npc_names import gen_npc_name, gen_npc_name_by_syllables
from .chargen import roll_stats
from .forms import ClassChoiceForm
from .chargen import PC_Character
from .game_facts import talents_dict

# Create your views here.


def npc_name(request):
    gen_name = gen_npc_name_by_syllables()

    ancestries = ["Dwarf", "Elf", "Goblin", "Halfling", "Half-Orc", "Human"]
    name_per_ancestry = {anc: gen_npc_name(anc) for anc in ancestries}

    return render(
        request,
        template_name="generators/npc_names.html",
        context={"gen_name": gen_name, "names_dict": name_per_ancestry},
    )


def get_stats(request):
    stats, best = roll_stats()
    context = {"stats": stats, "best": best, "form": ClassChoiceForm()}
    request.session["stats_d"] = stats
    request.session["character"] = {}
    print(f"{request.session['character']=}")
    return render(request, template_name="generators/get_stats.html", context=context)


def create_PC(request):
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = ClassChoiceForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            ancestry = int(form.cleaned_data.get("ancestry"))
            background = int(form.cleaned_data.get("background"))
            class_ = int(form.cleaned_data.get("class_"))
            stats_d = request.session.get("stats_d")
            character = PC_Character(
                stats_d,
                ancestry,
                background,
                class_,
                known_talents=[],
                first_creation=True,
            )
            stats_zip = character.get_stats()
            talents = talents_dict.get(character.class_)
            request.session["character"] = character.save()

            return render(
                request,
                template_name="generators/display_character.html",
                context={
                    "character": character,
                    "stats_zip": stats_zip,
                    "talents": talents,
                },
            )
    else:
        return redirect(get_stats)


def level_up_PC(request):
    char_values = request.session.get("character")

    if not char_values:
        return redirect(get_stats)
    character = PC_Character(**char_values, first_creation=False)
    character.level_up()
    request.session["character"] = character.save()
    stats_zip = character.get_stats()
    talents = talents_dict.get(character.class_)

    return render(
        request,
        template_name="generators/display_character.html",
        context={
            "character": character,
            "stats_zip": stats_zip,
            "talents": talents,
        },
    )

generators/templates/generators/display_character.html
{% extends "base.html" %}

{% block title %}
Character detail
{% endblock %}
{% block content %}
<table class="table table-striped">
    <tr>
        <td>Class</td>
        <td>{{character.class_}}</td>
    </tr>
    <tr>
        <td>Level</td>
        <td> {{character.level}}
        </td>
    </tr>
    <tr>
        <td>Ancestry</td>
        <td>{{character.ancestry}}<br>{{character.ancestry_feat|safe}}</td>
    </tr>
    <tr>
        <td>Background</td>
        <td>{{character.background}} {{character.background_description}}</td>
    </tr>
    <tr>
        <td>HP</td>
        <td>{{character.hp}}</td>
    </tr>

    <tr>
        <td>Talents</td>
        <td>
            <ul>
                {% for talent in character.talents%}
                <li>{{talent}}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
</table>
<table class="table table-striped">
    <tr>
        <th>Stat</th>
        <th>Value</th>
        <th>MOD</th>
    </tr>
    {% for stat_name, value, mod in stats_zip %}
    <tr>
        <td>{{stat_name}}</td>
        <td>{{value}}</td>
        <td>{% if mod >= 0 %}+{% endif %}{{mod}}</td>
    </tr>

    {% endfor %}

</table>


<a href="{% url 'generators:level_up_pc' %}" class="btn btn-primary btn-lg active" role="button"
    aria-pressed="true">Level UP</a>

<table class="table table-striped">
    <tr>
        <th>2d6</th>
        <th>{{character.class_}} Talents</th>
    </tr>
    {% for roll, talent in talents.items %}
    <tr>
        <td>{{roll}}</td>
        <td>{{talent}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

generators/templates/generators/get_stats.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block title %}
PC Stats
{% endblock %}
{% block content %}



<h2>You just rolled these stats, now deal with it</h2>

<table class="table table-striped">
    {% for stat_name, value in stats.items %}
    <tr>
        <th>{{stat_name}}</th>
        <td>{{value}}</td>
    </tr>
    {% endfor %}

</table>

{% if best <= 10 %} <h2>What a shitty character you rolled.</h2>

    <a href="{% url 'generators:get_stats' %}" class="btn btn-primary btn-lg active" role="button"
        aria-pressed="true">Roll again</a>

    <br><br>
    {% endif %}

    <h2>Choose your ABC</h2>

    {% crispy form %}

    {% endblock %}

generators/templates/generators/npc_names.html
{% extends "base.html" %}
{% block title %}
NPC Names
{% endblock %}
{% block content %}




<table class="table table-striped">
    {% for anc, name in names_dict.items %}
    <tr>
        <th>{{anc}}</th>
        <td>{{name}}</td>
    </tr>
    {% endfor %}
    <tr>
        <th>Randomly assembled name</th>
        <td>{{gen_name}}</td>
    </tr>

</table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- boostrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}ShadowDark Generators{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🧙‍♂️</text></svg>">

</head>

<body>


    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">ShadowDark Generators</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li><a class="nav-link" href="{% url 'generators:npc_name' %}">NPC Names</a></li>
                <li><a class="nav-link" href="{% url 'generators:get_stats' %}">Create a PC</a></li>
            </ul>
        </div>


    </nav>
    <br>

    {% endblock %}
    <div class="container">

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>
    <!-- Jquery and Popper-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>


    <!-- Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>



</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Home</h1>
{% load static %}

<br><br>


<p>This is definitely the home page.</p>
{% endblock %}